spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://www.ugsm.co.kr:5432/secret_present
    username: postgres
    password: ENC(MKujzeycyhKMvNQmUygv0e4ltif+Vw0+)
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(8yw6AScqYugrdE0u+xdcrOW8/O0IAyx+z9X3Gd6kPKWkMK5qnK5DtT2troDKNVWJ)
            client-secret: ENC(CGtVKEZpQgsoGlCfgNQixgND2nrN4sM1BIFQMDUd6aKUotU0oKlqaY0nlMbcUmKi)
            scope: profile_nickname, account_email, profile_image
            client-name: kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8081/api/login/oauth2/code/kakao
          naver:
            client-id: ENC(wf3iBVjGh9Vy7RuChW4C7B3Gqu1QCtLpcgaPQsN0Vrw=)
            client-secret: ENC(olVFZpWfxQQ7JrLYszgFpi2j952Lltuo)
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/api/login/oauth2/code/naver
          google:
            client-id: ENC(srj+CpCg5Z/duAAIOtBjAqvDvlG7WsyVrhI2lPvwGOZgjX8Rg5f7nuWdF1twJgV0uC3l9AV/RPGwpeneS641sxPtIgxH3JkKy4Qd8m5Gd3BcHYpxotHATg==)
            client-secret: ENC(7ORyxbYHwGfKmwnGa+uMV6oWelv0jwVU8EoNXJp4zUYWbqIIP6Oi/L62s86cqqO4)
            redirect-uri: http://localhost:8081/api/login/oauth2/code/google
            scope:
              - email
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
        SQL: debug

jwt:
  secret: ENC(Dnx6poJjIvCsOvlcqX6y5jac3+/pn9YMFHxQMrRk9a35euxjTnHlyQ==)
  redirect-host-on-success: localhost:8081

server:
  port: 8081